<a href="https://colab.research.google.com/github/CLKim00/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy란?

In [ ]:
# numpy 사용하기
import numpy as np

# 2. Array 정의 및 사용

In [ ]:
data1 = [1, 2, 3, 4, 5]
data1

[1, 2, 3, 4, 5]

In [ ]:
data2 = [1, 2, 3, 3.5, 4]
data2

[1, 2, 3, 3.5, 4]

In [ ]:
# numpy를 이용해 array 정의하기
# 위에서 만든 python list 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
# array의 형태(크기) 확인
arr1.shape

(5,)

In [ ]:
# python list를 직접 입력
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr2.shape

(5,)

In [ ]:
# array 자료형 확인
arr2.dtype

dtype('int64')

In [ ]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [ ]:
arr3.shape

(5,)

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
arr4 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr4.shape

(4, 3)

## 2-1. np.zeros(), np.ones(), np.arange() 함수
numpy에서 array를 정의할 때 사용되는 함수

In [ ]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든 요소가 0인 array를 만든다.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든 요소가 1인 array를 만든다.
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# np.arange() 함수는 인자로 받는 값만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값만큼의 크기를 가진다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

# 3. Array 연산
numpy의 연산은 크기가 동일한 array끼리 연산이 진행된다. 이 때 같은 위치에 있는 요소들끼리 연산이 된다.

In [ ]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2 = np.array([[10, 11, 12],[13, 14, 15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr2.shape

(2, 3)

## 3-1. Array 덧셈

In [ ]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

## 3-2. Array 뺄셈

In [ ]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

## 3-3. Array 곱셈

In [ ]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

## 3-4. Array 나눗셈

In [ ]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

## 3-5. Array의 브로드 캐스트
브로드캐스트란, 서로 크기가 다른 array의 연산을 제공한다.

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr3 = np.array([10, 11, 12])
arr3

array([10, 11, 12])

In [ ]:
arr3.shape

(3,)

In [ ]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [ ]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [ ]:
# 위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.
# 연산 결과를 살펴보면 arr3가 [10,11,12]에서 [[10,11,12],[10,11,12]]로 확장되어 계산되었음을 확인할 수 있다.

# 동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [ ]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

# 4. Array 인덱싱
numpy의 인덱싱은 python의 인덱싱과 동일하지만 1번째에서 시작하는 것이 아니라 0번째에서 시작하는 것에 주의한다.

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0번째 요소
arr1[0]

0

In [ ]:
# 3번째 요소
arr1[3]

3

In [ ]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1차원 이상의 인덱싱

In [ ]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 2차원의 array의 인덱싱은 2개의 인자 입력
arr2[0,0]

1

In [ ]:
# 2행의 모든 요소
arr2[2,:]

array([ 9, 10, 11, 12])

In [ ]:
# 2행의 3번째 요소
arr2[2,3]

12

In [ ]:
# 모든 행의 3번째 요소
arr2[:,3]

array([ 4,  8, 12])

# 5. Array boolean 인덱싱(마스크)
위에서 이용한 다차원 인덱싱을 응용해 boolean 인덱싱을 할 수 있다. 해당 기능은 주로 마스크라고 이야기하는데, boolean 인덱싱을 통해 만들어낸 array를 통해 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다. 즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [ ]:
names = np.array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park', 'Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [ ]:
names.shape

(8,)

In [ ]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재

data = np.random.randn(8,4)
data

array([[ 1.42045142,  0.36224344, -0.42868207,  0.59664106],
       [-0.76830986, -1.48458125,  0.04368187,  0.93664841],
       [-0.31895722, -1.14091038,  0.57366985,  0.06399942],
       [ 0.38649918, -0.49734581,  0.58403886, -1.53894322],
       [ 0.54016904,  0.38376502,  0.55627804,  0.09226111],
       [ 1.14892549,  0.10977836,  0.61219498, -0.7434224 ],
       [ 1.2165577 ,  1.48047813, -1.63307469, -2.47855039],
       [-0.38695725,  1.69532749,  1.14967093,  0.1607423 ]])

In [ ]:
data.shape

(8, 4)

In [ ]:
# names의 각 요소가 data의 각 행과 연결된다고 가정해보자.
# 그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.

# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [ ]:
data[names_Beomwoo_mask,:]    # 요소가 Beomwoo인 것에 대한 boolean값을 가지는 mask를 인덱싱에 응용하여 data의 0,1,5,7행을 꺼냄

array([[ 1.42045142,  0.36224344, -0.42868207,  0.59664106],
       [-0.76830986, -1.48458125,  0.04368187,  0.93664841],
       [ 1.14892549,  0.10977836,  0.61219498, -0.7434224 ],
       [-0.38695725,  1.69532749,  1.14967093,  0.1607423 ]])

In [ ]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim',:]

array([[-0.31895722, -1.14091038,  0.57366985,  0.06399942]])

In [ ]:
# 논리 연산을 응용해 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'),:]

array([[-0.31895722, -1.14091038,  0.57366985,  0.06399942],
       [ 1.2165577 ,  1.48047813, -1.63307469, -2.47855039]])

In [ ]:
# data array 자체적으로도 마스크를 만들고 응용하여 인덱싱이 가능하다.
# data array에서 0번째 열의 값이 음수인 행을 구해보자.

# 마스크 만들기
# data array에서 0번째 열이 음수인 요소의 boolean값은 다음과 같다.
data[:,0] < 0

array([False,  True,  True, False, False, False, False,  True])

In [ ]:
# 만든 마스크를 이용해 0번째 열이 음수인 행 구하기
data[data[:,0]<0,:]

array([[-0.76830986, -1.48458125,  0.04368187,  0.93664841],
       [-0.31895722, -1.14091038,  0.57366985,  0.06399942],
       [-0.38695725,  1.69532749,  1.14967093,  0.1607423 ]])

In [ ]:
# 특정 위치에 원하는 값 대입하기

# 0번째 열의 값이 음수인 행의 2,3번째 열의 값
data[data[:,0]<0,2:4]

array([[0.04368187, 0.93664841],
       [0.57366985, 0.06399942],
       [1.14967093, 0.1607423 ]])

In [ ]:
data[data[:,0]<0,2:4] = 0
data

array([[ 1.42045142,  0.36224344, -0.42868207,  0.59664106],
       [-0.76830986, -1.48458125,  0.        ,  0.        ],
       [-0.31895722, -1.14091038,  0.        ,  0.        ],
       [ 0.38649918, -0.49734581,  0.58403886, -1.53894322],
       [ 0.54016904,  0.38376502,  0.55627804,  0.09226111],
       [ 1.14892549,  0.10977836,  0.61219498, -0.7434224 ],
       [ 1.2165577 ,  1.48047813, -1.63307469, -2.47855039],
       [-0.38695725,  1.69532749,  0.        ,  0.        ]])

# 6. Numpy 함수

## 6-1. 하나의 array에 적용되는 함수

In [ ]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.64342817,  0.69192033, -0.82966441],
       [-0.04458924,  0.02631139,  0.95009122],
       [ 0.72226044, -1.85317637, -0.92741334],
       [ 0.53718689, -0.42208377,  0.05331377],
       [ 1.24493999,  1.0719583 , -0.9425513 ]])

In [ ]:
# 각 성분의 절대값 계산
np.abs(arr1)

array([[0.64342817, 0.69192033, 0.82966441],
       [0.04458924, 0.02631139, 0.95009122],
       [0.72226044, 1.85317637, 0.92741334],
       [0.53718689, 0.42208377, 0.05331377],
       [1.24493999, 1.0719583 , 0.9425513 ]])

In [ ]:
# 각 성분의 제곱근 계산 ( == array ** 0.5)
np.sqrt(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan, 0.83181749,        nan],
       [       nan, 0.16220785, 0.97472623],
       [0.84985907,        nan,        nan],
       [0.73293034,        nan, 0.23089775],
       [1.11576879, 1.03535419,        nan]])

In [ ]:
# 각 성분의 제곱 계산
np.square(arr1)

array([[4.13999806e-01, 4.78753747e-01, 6.88343038e-01],
       [1.98820077e-03, 6.92289138e-04, 9.02673323e-01],
       [5.21660137e-01, 3.43426267e+00, 8.60095500e-01],
       [2.88569753e-01, 1.78154708e-01, 2.84235813e-03],
       [1.54987558e+00, 1.14909459e+00, 8.88402952e-01]])

In [ ]:
# 각 성분을 무리수 e의 지수로 삼은 값 계산
np.exp(arr1)

array([[0.52548787, 1.99754781, 0.43619564],
       [0.95639024, 1.02666059, 2.58594553],
       [2.05908238, 0.15673851, 0.39557561],
       [1.71118633, 0.65567911, 1.05476055],
       [3.47272639, 2.92109428, 0.3896325 ]])

In [ ]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값 계산
np.log(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[        nan, -0.36828446,         nan],
       [        nan, -3.63775343, -0.05119728],
       [-0.32536949,         nan,         nan],
       [-0.62140922,         nan, -2.93156062],
       [ 0.21908733,  0.06948716,         nan]])

In [ ]:
np.log10(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[        nan, -0.15994391,         nan],
       [        nan, -1.57985624, -0.0222347 ],
       [-0.14130617,         nan,         nan],
       [-0.2698746 ,         nan, -1.2731606 ],
       [ 0.09514842,  0.03017789,         nan]])

In [ ]:
np.log2(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([[        nan, -0.53132216,         nan],
       [        nan, -5.24816883, -0.07386206],
       [-0.46940895,         nan,         nan],
       [-0.896504  ,         nan, -4.22934797],
       [ 0.3160762 ,  0.10024878,         nan]])

In [ ]:
# 각 성분의 부호 계산 (+인 경우는 1, -인 경우는 -1, 0인 경우는 0)
np.sign(arr1)

array([[-1.,  1., -1.],
       [-1.,  1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1.,  1.],
       [ 1.,  1., -1.]])

In [ ]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값 계산
np.ceil(arr1)

array([[-0.,  1., -0.],
       [-0.,  1.,  1.],
       [ 1., -1., -0.],
       [ 1., -0.,  1.],
       [ 2.,  2., -0.]])

In [ ]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값 계산
np.floor(arr1)

array([[-1.,  0., -1.],
       [-1.,  0.,  0.],
       [ 0., -2., -1.],
       [ 0., -1.,  0.],
       [ 1.,  1., -1.]])

In [ ]:
# 각 성분이 NaN인 경우 True, 아닌 경우 False 반환
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.isnan(np.log(arr1))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[ True, False,  True],
       [ True, False, False],
       [False,  True,  True],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
# 각 성분이 무한대인 경우 True, 아닌 경우 False 반환
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 성분에 대해 삼각함수 값을 계산 (cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[ 0.80004376,  0.77002223,  0.67512336],
       [ 0.99900606,  0.99965388,  0.58160889],
       [ 0.75031331, -0.27864222,  0.5999055 ],
       [ 0.85915161,  0.91223728,  0.99857916],
       [ 0.32012018,  0.47840549,  0.58772579]])

In [ ]:
np.tanh(arr1)

array([[-0.56722923,  0.59921424, -0.68029577],
       [-0.04455972,  0.02630532,  0.73982434],
       [ 0.61830752, -0.9520442 , -0.72938563],
       [ 0.49085559, -0.39868444,  0.05326332],
       [ 0.84685863,  0.79019787, -0.73639225]])

## 6-2. 두 개의 array에 적용되는 함수

In [ ]:
arr1

array([[-0.64342817,  0.69192033, -0.82966441],
       [-0.04458924,  0.02631139,  0.95009122],
       [ 0.72226044, -1.85317637, -0.92741334],
       [ 0.53718689, -0.42208377,  0.05331377],
       [ 1.24493999,  1.0719583 , -0.9425513 ]])

In [ ]:
arr2 = np.random.randn(5, 3)
arr2

array([[ 0.12745629, -0.11154995,  1.36029031],
       [-0.21019265, -0.89647126,  0.05957067],
       [ 0.85741094,  0.29309406, -0.10110737],
       [ 1.64201089,  0.12058119, -0.72849402],
       [ 0.6204536 ,  0.14080635,  2.48861092]])

In [ ]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값 게산(add, subtract, multiply, divide)
np.multiply(arr1, arr2)

array([[-0.08200897, -0.07718368, -1.12858446],
       [ 0.00937233, -0.0235874 ,  0.05659757],
       [ 0.619274  , -0.54315498,  0.09376832],
       [ 0.88206672, -0.05089536, -0.03883876],
       [ 0.77242749,  0.15093853, -2.34564346]])

In [ ]:
# 동일한 위치의 성분끼리 비교해 최대값 또는 최소값 계산(maximum, minimum)
np.maximum(arr1, arr2)

array([[ 0.12745629,  0.69192033,  1.36029031],
       [-0.04458924,  0.02631139,  0.95009122],
       [ 0.85741094,  0.29309406, -0.10110737],
       [ 1.64201089,  0.12058119,  0.05331377],
       [ 1.24493999,  1.0719583 ,  2.48861092]])

## 6-3. 통계 함수
통계 함수를 통해 array의 합이나 평균 등을 구할 때 추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균 등을 구할 수 있다.

In [ ]:
arr1

array([[-0.64342817,  0.69192033, -0.82966441],
       [-0.04458924,  0.02631139,  0.95009122],
       [ 0.72226044, -1.85317637, -0.92741334],
       [ 0.53718689, -0.42208377,  0.05331377],
       [ 1.24493999,  1.0719583 , -0.9425513 ]])

In [ ]:
# 전체 성분의 합
np.sum(arr1)

-0.3649242844293282

In [ ]:
# 열 간의 합
np.sum(arr1, axis = 1)

array([-0.78117225,  0.93181336, -2.05832928,  0.16841689,  1.37434699])

In [ ]:
# 행 간의 합
np.sum(arr1, axis = 0)

array([ 1.8163699 , -0.48507012, -1.69622406])

In [ ]:
# 전체 성분의 평균
np.mean(arr1)

-0.024328285628621882

In [ ]:
# 행 간의 평균
np.mean(arr1, axis = 0)

array([ 0.36327398, -0.09701402, -0.33924481])

In [ ]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1)

0.8698862253084896

In [ ]:
np.min(arr1, axis = 1)

array([-0.82966441, -0.04458924, -1.85317637, -0.42208377, -0.9425513 ])

In [ ]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1)    # 모든 원소를 1차원 array에 편 상태를 가정하고, argmax를 적용한 결과를 반환

7

In [ ]:
np.argmax(arr1, axis = 1)    # 가로 축 원소들끼리 비교하여 각 가로축 내부에서 argmax를 각각 적용

In [ ]:
np.argmax(arr1, axis = 0)    # 세로 축 원소들끼리 비교하여 각 세로축 내부에서 argmax를 각각 적용

array([4, 4, 1])

In [ ]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱 (cumsum, cumprod)
np.cumsum(arr1)

array([-0.64342817,  0.04849217, -0.78117225, -0.82576149, -0.7994501 ,
        0.15064111,  0.87290155, -0.98027482, -1.90768816, -1.37050127,
       -1.79258504, -1.73927127, -0.49433128,  0.57762701, -0.36492428])

In [ ]:
np.cumsum(arr1, axis = 1)

array([[-0.64342817,  0.04849217, -0.78117225],
       [-0.04458924, -0.01827786,  0.93181336],
       [ 0.72226044, -1.13091594, -2.05832928],
       [ 0.53718689,  0.11510312,  0.16841689],
       [ 1.24493999,  2.31689829,  1.37434699]])

In [ ]:
np.cumprod(arr1)

array([-6.43428167e-01, -4.45201031e-01,  3.69367452e-01, -1.64698158e-02,
       -4.33343714e-04, -4.11716057e-04, -2.97366219e-04,  5.51072051e-04,
       -5.11071571e-04, -2.74540947e-04,  1.15879278e-04,  6.17796122e-06,
        7.69119098e-06,  8.24463599e-06, -7.77099236e-06])

## 6-4. 기타 함수

In [ ]:
arr1

array([[-0.64342817,  0.69192033, -0.82966441],
       [-0.04458924,  0.02631139,  0.95009122],
       [ 0.72226044, -1.85317637, -0.92741334],
       [ 0.53718689, -0.42208377,  0.05331377],
       [ 1.24493999,  1.0719583 , -0.9425513 ]])

In [ ]:
# 전체 성분 오름차순 정렬
np.sort(arr1)

array([[-0.82966441, -0.64342817,  0.69192033],
       [-0.04458924,  0.02631139,  0.95009122],
       [-1.85317637, -0.92741334,  0.72226044],
       [-0.42208377,  0.05331377,  0.53718689],
       [-0.9425513 ,  1.0719583 ,  1.24493999]])

In [ ]:
# 전체 성분 내림차순 정렬
np.sort(arr1)[::-1]

array([[-0.9425513 ,  1.0719583 ,  1.24493999],
       [-0.42208377,  0.05331377,  0.53718689],
       [-1.85317637, -0.92741334,  0.72226044],
       [-0.04458924,  0.02631139,  0.95009122],
       [-0.82966441, -0.64342817,  0.69192033]])

In [ ]:
# 행 방향으로 오름차순 정렬
np.sort(arr1, axis = 0)

array([[-0.64342817, -1.85317637, -0.9425513 ],
       [-0.04458924, -0.42208377, -0.92741334],
       [ 0.53718689,  0.02631139, -0.82966441],
       [ 0.72226044,  0.69192033,  0.05331377],
       [ 1.24493999,  1.0719583 ,  0.95009122]])